backend:
  sliding_window_size: 14 # [keyframes]
  init_time_window: 2.0 # [sec.]
  solver_iterations: 5 
  isam2_relinearize_threshold: 0.01 # frobenius norm for relinearization on state variables

lidar_frontend:
  voxel_size: 0.5 # [m]
  undistort: false # generic LiDAR time offsets currently not supported
  knn_radius: 1.5 # [m], NOTE that a larger radius significantly increases search time
  knn_neighbors: 5
  normal_consistency_threshold: 0.8 # [0-1], accepting new points based updated normal consistency
  planarity_check:
    linearity: 0.3
    planarity: 0.3
  clustering:
    min_points: 5
    max_points: 20
    max_plane_thickness: 0.004 # [m]^2, NOTE: needs to be squared, residuals & thickness values are too
    sampling_voxel_size: 2.5 # [m], voxel size to use for cluster supplementation (0 = all)
    insert_lag: 0 # keyframe delay to use when inserting new clusters from keyframes
  keyframe:
    thresh_distance: 0.2 # [m]
    thresh_angle: 0.1745 # [rad], ~10[°]
    thresh_elapsed_scans: 2

camera_frontend:
  color_space: RGB # can be RGB or BGR (both 8-bit)
  colorize_scans: false # if enabled, will colorize points within the image
  sync_tolerance: 0.01 # [sec.], tolerance for syncing images to LiDAR scans
  keepalive_window: 0.6 # [sec.], how long images are kept for sync before being discarded

recovery:
  voxel_size: 0.2 # [m], voxel size to use for recovery reference point cloud
  reference_window_size: 10 # [keyframes], number of keyframes to use for recovery reference
  reference_lag: 2 # keyframe delay to use for recovery reference
  icp_iterations: 50
  max_correspondence_distance: 0.05 # [m], max. dist. for point-to-plane ICP correspondences

point_filter:
  min_distance: 2.5 # [m]
  max_distance: 100.0 # [m]

extrinsics:
  temporal_calibration_enabled: false
  extrinsic_calibration_enabled: false
  imu_T_lidar: # initial guess for (or constant) extrinsic IMU-LiDAR calibration
    translation: [-0.00695, -0.00671,  0.04989] # [m]
    rotation: [0.70944, -0.70477,  0.00114, -0.00025] # hamilton quaternion (x, y, z, w)
  imu_t_lidar: 0.001585 # initial guess for (or constant) temporal IMU-LiDAR offset
  imu_T_camera: # currently unused
    translation: [0, 0, 0]
    rotation: [0, 0, 0, 1] # (x, y, z, w)
    
intrinsics:
  camera:
    model: "PinholeRadTan" # or "PinholeEquidistant", but not supported yet
    pinhole_parameters: # 640x480
      fx: 807.406
      fy: 806.768
      cx: 327.545
      cy: 233.247
    distortion_coefficients:
      - -0.501859
      - 0.270368
      - 0.000114465
      - -0.00185591

