# NOTE: these calibrations are approximate
# and should be used to initialize online
# extrinsic calibration in your estimator

# transformation from /livox/imu to /livox/lidar
I_Tf_L:
  [
    [1.       0.       0.      -0.011],
    [0.       1.       0.      -0.02329],
    [0.       0.       1.      -0.04412],
    [0.       0.       0.       1.],
  ]
# transformation from /livox_imu to /image_raw
I_Tf_C:
  [
    [0.          0.17364818  0.98480775  0.026613],
    [-1.          0.          0.         -0.02329],
    [0.         -0.98480775  0.17364818 -0.088417],
    [0.          0.          0.          1.],
  ]
